import { ArrowRight, Check, Languages, PlayCircle, Sparkles, Subtitles, WandSparkles } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';

const products = {
  '/ai-dubbing': { eyebrow: 'AI dubbing', title: 'Make every video speak a new language.', description: 'Translate dialogue, choose a natural voice, and create a timed dubbed track without leaving your video workspace.', icon: Languages, accent: 'bg-cyan-100 text-cyan-700', points: ['Translate into 10+ languages', 'Choose accent, gender, and speaking style', 'Keep generated audio aligned to the edit'], link: '/tools' },
  '/ai-subtitles': { eyebrow: 'AI subtitles', title: 'Captions that keep up with your story.', description: 'Transcribe speech, segment captions, translate subtitles, and export polished SRT or VTT files from one workflow.', icon: Subtitles, accent: 'bg-rose-100 text-rose-700', points: ['Automatic transcription and timing', 'Editable subtitle styling and translation', 'Export SRT and VTT files'], link: '/tools/subtitles' },
  '/ai-translation': { eyebrow: 'AI translation', title: 'Translate meaning, not just words.', description: 'Turn your transcript into a clear, audience-ready translation with controls for tone, style, and review.', icon: WandSparkles, accent: 'bg-violet-100 text-violet-700', points: ['Natural, literal, formal, and professional styles', 'Review and edit every translated segment', 'Regenerate translations as your transcript changes'], link: '/tools/translation' },
} as const;

export default function ProductPage() {
  const product = products[useLocation().pathname as keyof typeof products] ?? products['/ai-dubbing'];
  const Icon = product.icon;
  return <div className="mx-auto max-w-7xl px-6 py-10"><section className="grid items-center gap-12 py-12 md:grid-cols-2 md:py-20"><div><span className={`inline-flex rounded-full px-3 py-1 text-xs font-medium uppercase tracking-[0.2em] ${product.accent}`}><Sparkles className="mr-2 h-3.5 w-3.5" /> {product.eyebrow}</span><h1 className="mt-6 max-w-2xl text-5xl font-semibold leading-tight tracking-tight md:text-6xl">{product.title}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-muted-foreground">{product.description}</p><div className="mt-8 flex flex-wrap gap-4"><Link className="btn-primary" to="/signup">Start creating <ArrowRight className="ml-2 h-4 w-4" /></Link><Link className="btn-secondary" to={product.link}>Explore the tool</Link></div></div><div className="card overflow-hidden p-5"><div className="rounded-xl bg-slate-950 p-5 text-white sm:p-8"><div className="flex items-center justify-between"><span className="rounded-xl bg-primary p-3"><Icon className="h-7 w-7" /></span><span className="text-xs uppercase tracking-[0.18em] text-slate-400">VideoForge workspace</span></div><div className="mt-12 rounded-xl border border-slate-700 bg-slate-900 p-5"><div className="flex items-center justify-between text-sm text-slate-400"><span>Project / Product launch</span><PlayCircle className="h-5 w-5 text-cyan-300" /></div><div className="mt-6 h-2 rounded-full bg-slate-700"><div className="h-full w-3/5 rounded-full bg-primary" /></div><p className="mt-6 text-sm text-slate-400">Source transcript</p><p className="mt-2 font-medium">“Let’s launch the next big idea.”</p><div className="mt-5 border-t border-slate-700 pt-5"><p className="text-sm text-cyan-300">{product.eyebrow}</p><p className="mt-2 font-medium">Ready for review, editing, and export.</p></div></div></div></div></section><section className="grid gap-4 border-t border-border py-14 md:grid-cols-3">{product.points.map((point) => <div className="card p-5" key={point}><Check className="h-5 w-5 text-success" /><p className="mt-4 font-medium">{point}</p></div>)}</section></div>;
}
